apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolesenseai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolesenseai
  template:
    metadata:
      labels:
        app: rolesenseai
    spec:
      containers:
      - name: rolesenseai
        image: rolesenseai:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_DATABASE
          value: "rolesenseai"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: rolesenseai-service
spec:
  selector:
    app: rolesenseai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "rolesenseai"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
